Evolutionary Algorithms for Financial Optimisation: bond::BondHelper< T > Class Template Reference
bond::BondHelper< T > Class Template Reference
A class for the bond pricing problem as well as finding the yield-to-maturities of bonds.
#include <bond.h>
Public Member Functions
BondHelper (const std::vector< Bond< T >> &i_bonds, const DF_type &i_df_type)
Constructor.
template<typename S >
std::vector< T > set_init_nss_params (const S &solver)
This method sets the nss initial svensson parameters by computing the bond yields-to-maturity and Macaulay durations.
template<typename S1 , typename S2 >
void bond_pricing (const S1 &solver, const S2 &solver_irr, const Bond_pricing_type &bond_pricing_type)
This methods solves the bond pricing problem using prices or yields and the supplied solver.
template<typename S >
void print_bond_pricing_results (const std::vector< T > &res, const S &solver_irr)
This method prints to screen the bond pricing results.
Private Member Functions
T estimate_bond_pricing (const std::vector< T > &solution, const T &coupon_value, const T &nominal_value, const std::vector< T > &time_periods)
Returns the bond prices using the estimated spot interest rates computed with svensson.
template<typename S >
T fitness_bond_pricing_yields (const std::vector< T > &solution, const S &solver_irr, const bool &use_penalty_method)
This is the fitness function for bond pricing using the bonds' yields-to-maturity.
T fitness_bond_pricing_prices (const std::vector< T > &solution, const bool &use_penalty_method)
This is the fitness function for bond pricing using the bonds' prices.
Private Attributes
std::vector< Bond< T > > bonds
Vector of bonds.
const DF_type df_type
Discount Factor type.
Detailed Description
template<typename T>
class bond::BondHelper< T >
A class for the bond pricing problem as well as finding the yield-to-maturities of bonds.
Definition at line 26 of file bond.h.
Constructor & Destructor Documentation
BondHelper()
template<typename T > bond::BondHelper< T >::BondHelper (const std::vector< Bond< T >> & i_bonds, const DF_type & i_df_type = DF_type::exp) inline
Constructor.
Parameters
i_bonds A vector of Bond<T> objects
i_df_type The type of discount factor method
Returns
A BondHelper<T> object
Definition at line 66 of file bondhelper.h.
                                                                                 :
             bonds( i_bonds ),
             df_type( i_df_type )
         {};
Member Function Documentation
bond_pricing()
template<typename T > template<typename S1 , typename S2 > void bond::BondHelper< T >::bond_pricing (const S1 & solver, const S2 & solver_irr, const Bond_pricing_type & bond_pricing_type)
This methods solves the bond pricing problem using prices or yields and the supplied solver.
Parameters
solver The parameter structure of the solver that is going to be used for bond pricing
solver_irr The parameter structure of the solver that is going to be used to estimate the yield of maturity
bond_pricing_type Whether to use bond yields-to-maturities or bond prices to find the NSS parameters
Returns
void
Definition at line 235 of file bondhelper.h.
References bond::bpp, bond::bpy, nss::constraints_svensson(), and ea::solve().
     {
         assert(solver.ndv == 6);
         for (const auto& p : bonds)
         {
             assert(p.yield > 0 && p.yield < 1);
             assert(p.duration > 0);
         }
         switch (bond_pricing_type)
         {
         case(Bond_pricing_type::bpp):
         {
             auto f = [&, use_penalty_method = solver.use_penalty_method](const auto& solution) { return fitness_bond_pricing_prices(solution, use_penalty_method); };
             auto c = [&, constraints_type = solver.constraints_type](const auto& solution) { return constraints_svensson(solution, constraints_type); };
             std::cout << "Solving bond pricing using bond prices..." << "\n";
             auto res = solve(f, c, solver, "BPP");
             print_bond_pricing_results(res, solver_irr);
             break;
         }
         case(Bond_pricing_type::bpy):
         {
             auto f = [&, use_penalty_method = solver.use_penalty_method](const auto& solution) { return fitness_bond_pricing_yields(solution, solver_irr, use_penalty_method); };
             auto c = [&, constraints_type = solver.constraints_type](const auto& solution) { return constraints_svensson(solution, constraints_type); };
             std::cout << "Solving bond pricing using bond yields..." << "\n";
             auto res = solve(f, c, solver, "BPY");
             print_bond_pricing_results(res, solver_irr);
         }
         }
     }
estimate_bond_pricing()
template<typename T > T bond::BondHelper< T >::estimate_bond_pricing (const std::vector< T > & solution, const T & coupon_value, const T & nominal_value, const std::vector< T > & time_periods) private
Returns the bond prices using the estimated spot interest rates computed with svensson.
Parameters
solution NSS parameters candindate solution
coupon_value The value of the coupon payment
nominal_value The nominal value of the investment
time_periods The time periods that correspond to the coupon payments
Returns
The price of the bond
Call svensson for period
Definition at line 178 of file bondhelper.h.
References irr::compute_discount_factor(), and nss::svensson().
     {
         T sum = 0.0;
         for (const auto& t : time_periods)
         {
             sum = sum + coupon_value * compute_discount_factor(svensson(solution, t), t, df_type);
         }
         T m = time_periods.back();
         sum = sum + nominal_value * compute_discount_factor(svensson(solution, m), m, df_type);
         return sum;
     }
fitness_bond_pricing_prices()
template<typename T > T bond::BondHelper< T >::fitness_bond_pricing_prices (const std::vector< T > & solution, const bool & use_penalty_method) private
This is the fitness function for bond pricing using the bonds' prices.
Parameters
solution NSS parameters candindate solution
use_penalty_method Whether to use the penalty method defined for NSS or not
Returns
The fitness cost of NSS for bond pricing
The sum of squares of errors between the actual bond price and the estimated price from estimate_bond_pricing
Definition at line 192 of file bondhelper.h.
References nss::penalty_svensson().
     {
         T sum_of_squares = 0.0;
         for (const auto& k : bonds)
         {
             T estimate = estimate_bond_pricing(solution, k.coupon_value, k.nominal_value, k.time_periods);
             sum_of_squares = sum_of_squares + std::pow((k.price/100 - estimate/100), 2) / std::sqrt(k.duration);
         }
         if (use_penalty_method)
         {
             return sum_of_squares + penalty_svensson(solution);
         }
         else
         {
             return sum_of_squares;
         }
     }
fitness_bond_pricing_yields()
template<typename T > template<typename S > T bond::BondHelper< T >::fitness_bond_pricing_yields (const std::vector< T > & solution, const S & solver_irr, const bool & use_penalty_method) private
This is the fitness function for bond pricing using the bonds' yields-to-maturity.
Parameters
solution NSS parameters candindate solution
solver_irr The parameter structure of the solver that is going to be used to estimate the yield of maturity
use_penalty_method Whether to use the penalty method defined for NSS or not
Returns
The fitness cost of NSS for bond pricing
The sum of squares of errors between the actual bond yield to maturity and the estimated yield to maturity by svensson is used
Definition at line 213 of file bondhelper.h.
References nss::penalty_svensson().
     {
         T sum_of_squares = 0;
         for (const auto& k : bonds)
         {
             T estimate_price = estimate_bond_pricing(solution, k.coupon_value, k.nominal_value, k.time_periods);
             T estimate = k.compute_yield(estimate_price, solver_irr, df_type);
             sum_of_squares = sum_of_squares + std::pow(k.yield - estimate, 2);
         }
         if (use_penalty_method)
         {
             return sum_of_squares + penalty_svensson(solution);
         }
         else
         {
             return sum_of_squares;
         }
     }
print_bond_pricing_results()
template<typename T > template<typename S > void bond::BondHelper< T >::print_bond_pricing_results (const std::vector< T > & res, const S & solver_irr)
This method prints to screen the bond pricing results.
Parameters
res The solution vector of NSS parameters
solver_irr The parameter structure of the solver that is going to be used to estimate the yield of maturity
Returns
void
Definition at line 267 of file bondhelper.h.
     {
         T error = 0;
         //for (const auto& p : bonds)
         //{
             //T estimate_price = estimate_bond_pricing(res, p.coupon_value, p.nominal_value, p.time_periods);
             //T estimate = p.compute_yield(estimate_price, solver_irr, df_type);
             //error = error + std::pow(estimate - p.yield, 2);
             //std::cout << "Estimated yield: " << estimate << " Actual Yield: " << p.yield << "\n";
         //}
         //std::cout << "Yield Mean Squared Error: " << error << "\n";
         error = 0;
         for (const auto& p : bonds)
         {
             error = error + std::pow(estimate_bond_pricing(res, p.coupon_value, p.nominal_value, p.time_periods)/100 - p.price/100, 2);
             std::cout << "Estimated price: " << estimate_bond_pricing(res, p.coupon_value, p.nominal_value, p.time_periods) << " Actual Price: " << p.price << "\n";
         }
         std::cout << "Price Mean Squared Error: " << error << "\n";
     }
set_init_nss_params()
template<typename T > template<typename S > std::vector< T > bond::BondHelper< T >::set_init_nss_params (const S & solver)
This method sets the nss initial svensson parameters by computing the bond yields-to-maturity and Macaulay durations.
Parameters
solver The parameter structure of the solver that is going to be used
Returns
A vector of decision variables for NSS
Definition at line 69 of file bondhelper.h.
References bond::BondHelper< T >::set_init_nss_params().
Referenced by bond::BondHelper< T >::set_init_nss_params().
Member Data Documentation
bonds
template<typename T > std::vector<Bond<T> > bond::BondHelper< T >::bonds private
Vector of bonds.
Definition at line 93 of file bondhelper.h.
df_type
template<typename T > const DF_type bond::BondHelper< T >::df_type private
Discount Factor type.
Definition at line 95 of file bondhelper.h.
The documentation for this class was generated from the following files:
bond.h
bondhelper.h