Evolutionary Algorithms for Financial Optimisation: ea::Solver< GA, T, F, C > Class Template Reference
ea::Solver< GA, T, F, C > Class Template Reference
Genetic Algorithms (GA) Class.
#include <geneticalgo.h>
Public Member Functions
Solver (const GA< T > &i_ga, F f, C c)
Constructor.
Public Member Functions inherited from ea::Solver_base< Solver< GA, T, F, C >, GA, T, F, C >
std::vector< T > solver_bench (const std::string &problem_name)
Solve wrapper function for Solvers, used for benchmarks.
Private Member Functions
std::vector< T > crossover (std::vector< T > r, std::vector< T > s)
Crossover step of GA.
std::vector< T > selection ()
Selection step of GA.
std::vector< T > mutation (const std::vector< T > &individual)
Mutation step of GA.
size_t nkeep ()
Returns number of individuals to be kept in each generation.
void run_algo ()
Runs the algorithm until stopping criteria return void.
std::stringstream display_parameters ()
Display the parameters of GA.
Private Attributes
const GA< T > & ga
Genetic Algorithms structure used internally (reference to solver_struct)
size_t npop
Size of the population is mutable.
std::vector< T > stdev
Standard deviation is mutable, so a copy is created.
boost::math::beta_distribution< T > bdistribution
Beta distribution.
Friends
class Solver_base< Solver< GA, T, F, C >, GA, T, F, C >
Additional Inherited Members
Protected Member Functions inherited from ea::Solver_base< Solver< GA, T, F, C >, GA, T, F, C >
Solver_base (const GA< T > &i_solver_struct, const F &i_f, const C &i_c)
Constructor.
std::vector< T > randomise_individual ()
Returns a randomised individual using the initial decision variables and standard deviation.
std::vector< std::vector< T > > init_individuals ()
Initialises the population by randomising aroung the decision variables using the given standard deviation.
void find_min_cost ()
Find the minimum cost individual of the fitness function for the population.
std::stringstream display_results ()
Display the results of execution of an algorithm as well as its parameters.
void write_results_to_file (const std::string &problem_name)
Write the results to a file.
Protected Attributes inherited from ea::Solver_base< Solver< GA, T, F, C >, GA, T, F, C >
const GA< T > solver_struct
Internal copy of the structure used for parameters of the algorithm.
F f
Copy of the fitness function passed as a lambda.
C c
Copy of the constraints function passed as a lambda.
std::vector< std::vector< T > > individuals
Population.
std::vector< T > min_cost
Best solution / lowest fitness.
size_t last_iter
Last iteration to solution.
bool solved_flag
A flag which determines if the solver has already solved the problem.
T timer
The timer used for benchmarks.
std::uniform_real_distribution< T > distribution
Uniform real distribution.
Detailed Description
template<typename T, typename F, typename C>
class ea::Solver< GA, T, F, C >
Genetic Algorithms (GA) Class.
Definition at line 73 of file geneticalgo.h.
Constructor & Destructor Documentation
Solver()
template<typename T , typename F , typename C > ea::Solver< GA, T, F, C >::Solver (const GA< T > & i_ga, F f, C c) inline
Constructor.
Parameters
i_ga The genetic algorithms parameter structure that is used to construct the solver
f A reference to the objective function
c A reference to the constraints function
Returns
A Solver<GA, T, F, C> object
Definition at line 84 of file geneticalgo.h.
                                             :
             Solver_base<Solver<GA, T, F, C>, GA, T, F, C> ( i_ga, f, c ),
             ga ( this->solver_struct ),
             npop ( i_ga.npop ),
             stdev ( i_ga.stdev ),
             bdistribution (boost::math::beta_distribution<T>(1, ga.alpha))
         {
         }
Member Function Documentation
crossover()
template<typename T , typename F , typename C > std::vector< T > ea::Solver< GA, T, F, C >::crossover (std::vector< T > r, std::vector< T > s) private
Crossover step of GA.
Parameters
r,s Parent individuals
Returns
An offspring from the two parents r and s
Definition at line 152 of file geneticalgo.h.
References ea::generator().
     {
         std::vector<T> offspring(ga.ndv);
         std::vector<T> psi(ga.ndv);
         for (size_t j = 0; j < ga.ndv; ++j)
         {
             psi[j] = this->distribution(generator);
             offspring[j] = psi[j] * r[j] + (1 - psi[j]) * s[j];
         }
         return offspring;
     }
display_parameters()
template<typename T , typename F , typename C > ea::Solver< GA, T, F, C >::display_parameters () inline private
Display the parameters of GA.
Returns
A std::stringstream of the parameters
Definition at line 133 of file geneticalgo.h.
References ea::GA< T >::alpha, ea::keep_same, ea::GA< T >::pi, ea::re_mutate, ea::remove, ea::GA< T >::strategy, and ea::GA< T >::x_rate.
         {
             std::stringstream parameters;
             parameters << "Natural Selection Rate:" << "," << ga.x_rate << ",";
             parameters << "Probability of Mutation:" << "," << ga.pi << ",";
             parameters << "Beta Distribution alpha:" << "," << ga.alpha << ",";
             parameters << "Strategy:" << ",";
             switch (ga.strategy)
             {
             case Strategy::keep_same: parameters << "Keep same individual"; break;
             case Strategy::re_mutate: parameters << "Re-mutate individual"; break;
             case Strategy::remove: parameters << "Remove individual"; break;
             default: parameters << "Do nothing"; break;
             }
             return parameters;
         }
mutation()
template<typename T , typename F , typename C > std::vector< T > ea::Solver< GA, T, F, C >::mutation (const std::vector< T > & individual) private
Mutation step of GA.
Parameters
individual An individual of the population
Returns
A mutated individual
Definition at line 178 of file geneticalgo.h.
References ea::generator().
     {
         std::vector<T> mutated = individual;
         for (size_t j = 0; j < ga.ndv; ++j)
         {
             const T r = this->distribution(generator);
             if (ga.pi < r)
             {
                 std::normal_distribution<T> ndistribution(0, stdev[j]);
                 T epsilon = ndistribution(generator);
                 mutated[j] = mutated[j] + epsilon;
             }
         }
         return mutated;
     }
nkeep()
template<typename T , typename F , typename C > size_t ea::Solver< GA, T, F, C >::nkeep () private
Returns number of individuals to be kept in each generation.
Returns
The new nkeep
Definition at line 195 of file geneticalgo.h.
     {
         return static_cast<size_t>(std::ceil(static_cast<T>(npop) * ga.x_rate));
     }
run_algo()
template<typename T , typename F , typename C > void ea::Solver< GA, T, F, C >::run_algo () private
Runs the algorithm until stopping criteria return void.
Set the new population size which is previous population size + natural selection rate * population size
Standard Deviation is not constant in GA
Definition at line 201 of file geneticalgo.h.
References ea::keep_same, ea::none, ea::re_mutate, and ea::remove.
     {
         auto comparator = [&](const std::vector<T>& l, const std::vector<T>& r)
         {
             return this->f(l) < this->f(r);
         };
         for (size_t iter = 0; iter < ga.iter_max; ++iter)
         {
             npop = this->individuals.size();
             std::sort(this->individuals.begin(), this->individuals.end(), comparator);
             this->individuals.erase(this->individuals.begin() + nkeep(), this->individuals.begin() + this->individuals.size());
             this->min_cost = this->individuals[0];
             this->last_iter = iter;
             if (ga.tol > std::abs(this->f(this->min_cost)))
             {
                 this->solved_flag = true;
                 break;
             }
             for (size_t i = 0; i < npop; ++i)
             {
                 std::vector<T> offspring = selection();
                 this->individuals.push_back(offspring);
             }
             if (this->individuals.size() > 1000)
             {
                 //this->individuals.erase(this->individuals.begin() + 1000, this->individuals.begin() + this->individuals.size());
             }
             for (size_t i = 1; i < this->individuals.size(); ++i)
             {
                 std::vector<T> mutated = mutation(this->individuals[i]);
                 if (!this->c(mutated))
                 {
                     switch (ga.strategy)
                     {
                     case Strategy::keep_same: this->individuals[i] = this->individuals[i]; break;
                     case Strategy::re_mutate:
                     {
                         while (!this->c(mutated))
{
                             mutated = mutation(this->individuals[i]);
                         }
                         break;
                         this->individuals[i] = mutated;
                     }
                     case Strategy::remove:
                     {
                         if (i == this->individuals.size() - 1)
{
                             this->individuals.pop_back();
                         }
                         else
{
                             this->individuals.erase(this->individuals.begin() + i, this->individuals.begin() + i + 1);
                         }
                         break;
                     }
                     case Strategy::none: break;
                     default: std::abort();
                     }
                 }
                 else
                 {
                     this->individuals[i] = mutated;
                 }
             }
             for (auto& p : stdev)
             {
                 p = p + 0.02 * p;
             }
         }
     }
selection()
template<typename T , typename F , typename C > std::vector< T > ea::Solver< GA, T, F, C >::selection () private
Selection step of GA.
Select two parents r and s using a Beta distribution and generates an offspring using the crossover method
Returns
An offspring from the two parents
Generate r and s indices
Produce offsrping using r and s indices by crossover
Definition at line 165 of file geneticalgo.h.
References ea::generator().
     {
         T xi = quantile(bdistribution, this->distribution(generator));
         size_t r = static_cast<size_t>(std::floor(static_cast<T>(nkeep()) * xi));
         xi = quantile(bdistribution, this->distribution(generator));
         size_t s = static_cast<size_t>(std::floor(static_cast<T>(nkeep()) * xi));
         std::vector<T> offspring = crossover(this->individuals[r], this->individuals[s]);
         return offspring;
     }
Friends And Related Function Documentation
Solver_base< Solver< GA, T, F, C >, GA, T, F, C >
template<typename T , typename F , typename C > friend class Solver_base< Solver< GA, T, F, C >, GA, T, F, C > friend
Definition at line 76 of file geneticalgo.h.
Member Data Documentation
bdistribution
template<typename T , typename F , typename C > boost::math::beta_distribution<T> ea::Solver< GA, T, F, C >::bdistribution private
Beta distribution.
Definition at line 100 of file geneticalgo.h.
ga
template<typename T , typename F , typename C > const GA<T>& ea::Solver< GA, T, F, C >::ga private
Genetic Algorithms structure used internally (reference to solver_struct)
Definition at line 94 of file geneticalgo.h.
npop
template<typename T , typename F , typename C > size_t ea::Solver< GA, T, F, C >::npop private
Size of the population is mutable.
Definition at line 96 of file geneticalgo.h.
stdev
template<typename T , typename F , typename C > std::vector<T> ea::Solver< GA, T, F, C >::stdev private
Standard deviation is mutable, so a copy is created.
Definition at line 98 of file geneticalgo.h.
The documentation for this class was generated from the following file:
geneticalgo.h