Evolutionary Algorithms for Financial Optimisation: yft::Interest_Rate_Helper< T > Class Template Reference
yft::Interest_Rate_Helper< T > Class Template Reference
A class for the yield-curve-fitting problem.
#include <yield_curve_fitting.h>
Public Member Functions
Interest_Rate_Helper (const std::vector< Interest_Rate< T >> &i_ir_vec)
Constructor.
template<typename S >
void yieldcurve_fitting (const S &solver)
Yield Curve Fitting using interest rates and recorded periods.
Private Member Functions
T fitness_yield_curve_fitting (const std::vector< T > &solution, const bool &use_penalty_method)
This is the fitness function for yield-curve fitting using Interest Rates.
Private Attributes
std::vector< Interest_Rate< T > > ir_vec
Vector of interest rates.
Detailed Description
template<typename T>
class yft::Interest_Rate_Helper< T >
A class for the yield-curve-fitting problem.
Definition at line 65 of file yield_curve_fitting.h.
Constructor & Destructor Documentation
Interest_Rate_Helper()
template<typename T > yft::Interest_Rate_Helper< T >::Interest_Rate_Helper (const std::vector< Interest_Rate< T >> & i_ir_vec) inline
Constructor.
Parameters
i_ir_vec A vector of Interest_Rate<T> objects
Returns
An Interest_Rate_Helper object
Definition at line 73 of file yield_curve_fitting.h.
                                                                           :
             ir_vec{ i_ir_vec } {};
Member Function Documentation
fitness_yield_curve_fitting()
template<typename T > yft::Interest_Rate_Helper< T >::fitness_yield_curve_fitting (const std::vector< T > & solution, const bool & use_penalty_method) inline private
This is the fitness function for yield-curve fitting using Interest Rates.
Parameters
solution NSS parameters candindate solution
use_penalty_method Whether to use the penalty method defined for NSS or not
Returns
The fitness cost of NSS for yield curve fitting
The sum of squares of errors betwwen the actual rates and the rates computed by svensson are used
Definition at line 105 of file yield_curve_fitting.h.
References nss::penalty_svensson(), and nss::svensson().
         {
             T sum_of_squares = 0;
             for (size_t i = 0; i < ir_vec.size(); ++i)
             {
                 T estimate = svensson(solution, ir_vec[i].period);
                 sum_of_squares = sum_of_squares + std::pow(ir_vec[i].rate - estimate, 2);
             }
             if (use_penalty_method)
             {
                 return sum_of_squares + penalty_svensson(solution);
             }
             else
             {
                 return sum_of_squares;
             }
         };
yieldcurve_fitting()
template<typename T > template<typename S > yft::Interest_Rate_Helper< T >::yieldcurve_fitting (const S & solver) inline
Yield Curve Fitting using interest rates and recorded periods.
Parameters
solver The parameter structure of the solver that is going to be used for yield curve fitting
Returns
void
Definition at line 81 of file yield_curve_fitting.h.
References nss::constraints_svensson(), ea::solve(), and nss::svensson().
         {
             assert(solver.ndv == 6);
             auto f = [&, use_penalty_method = solver.use_penalty_method](const auto& solution) { return fitness_yield_curve_fitting(solution, use_penalty_method); };
             auto c = [&, constraints_type = solver.constraints_type](const auto& solution) { return constraints_svensson(solution, constraints_type); };
             std::cout << "Yield Curve fitting." << "\n";
             auto res = solve(f, c, solver, "YFT");
             T error = 0;
             for (const auto& p : ir_vec)
             {
                 error = error + std::pow(svensson(res, p.period) - p.rate, 2);
                 //std::cout << "Estimated interest rates: " << svensson(res, p.period) << " Actual interest rates: " << p.rate << "\n";
             }
             std::cout << "Zero-rate Mean Squared Error: " << error / ir_vec.size() << "\n";
         };
Member Data Documentation
ir_vec
template<typename T > std::vector<Interest_Rate<T> > yft::Interest_Rate_Helper< T >::ir_vec private
Vector of interest rates.
Definition at line 95 of file yield_curve_fitting.h.
The documentation for this class was generated from the following file:
yield_curve_fitting.h