Evolutionary Algorithms for Financial Optimisation: bond::Bond< T > Class Template Reference
bond::Bond< T > Class Template Reference
Bond Class definition.
#include <bond.h>
Public Member Functions
Bond (const T &i_coupon_percentage, const T &i_price, const T &i_nominal_value, const T &i_frequency, std::string &i_settlement_date, const std::string &i_maturity_date)
Constructor.
template<typename S >
T compute_yield (const T &i_price, const S &solver, const DF_type &df_type) const
Calculates the yield-to-maturity using the supplied solver.
template<typename S >
T compute_yield (const T &i_price, const S &solver, const DF_type &df_type, const std::string &bonds_identifier) const
Calculates the yield-to-maturity using the supplied solver and passes the bond identifier to the solver.
T compute_macaulay_duration (const DF_type &df_type) const
Calculates the Macaulay duration of the bond.
Private Member Functions
std::vector< T > compute_cash_flows ()
Calculate the cash flows of the bond.
Private Attributes
const T coupon_percentage
Bond's annual coupon rate.
const T price
Bond's price.
const T nominal_value
Bond's face value.
const T frequency
Bond's coupon payment frequency.
const T coupon_value
This is the annual coupon divided by the frequency.
std::vector< T > time_periods
Coupon payment periods.
std::vector< T > cash_flows
A vector with all the coupon payments corresponding to time periods.
date::sys_days settlement_date
Settlement date of the bond.
date::sys_days maturity_date
Maturity date of the bond.
T yield
Yield-to-maturity of the bond.
T duration
Macaulay duration of the bond.
Friends
class BondHelper< T >
Friend class BondHelper.
Detailed Description
template<typename T>
class bond::Bond< T >
Bond Class definition.
Definition at line 32 of file bond.h.
Constructor & Destructor Documentation
Bond()
template<typename T > bond::Bond< T >::Bond (const T & i_coupon_percentage, const T & i_price, const T & i_nominal_value, const T & i_frequency, std::string & i_settlement_date, const std::string & i_maturity_date) inline
Constructor.
Parameters
i_coupon_percentage The coupon rate in %
i_price The price of the bond
i_nominal_value The nominal value of the bond
i_frequency The frequency of coupon payments per year
i_settlement_date The date the bond was bought
i_maturity_date The date the bond expires
Returns
A Bond<T> object
Definition at line 48 of file bond.h.
                                                                             :
             coupon_percentage{ i_coupon_percentage },
             price{ i_price },
             nominal_value{ i_nominal_value },
             frequency{ i_frequency },
             coupon_value{ coupon_percentage * nominal_value / frequency },
             yield{ 0 },
             duration{ 0 }
         {
             assert(price > 0);
             assert(coupon_percentage > 0 && coupon_percentage < 1);
             assert(nominal_value > 0);
             assert(frequency > 0);
             std::tm t1 {};
             std::tm t2 {};
             std::stringstream s1;
             std::stringstream s2;
             s1 << i_settlement_date;
             s2 << i_maturity_date;
             s1 >> std::get_time(&t1, "%Y-%m-%d");
             s2 >> std::get_time(&t2, "%Y-%m-%d");
             settlement_date = date::year(t1.tm_year) / (t1.tm_mon+1) / t1.tm_mday;
             maturity_date = date::year(t2.tm_year) / (t2.tm_mon+1) / t2.tm_mday;
             cash_flows = compute_cash_flows();
             time_periods.resize(cash_flows.size());
             for (size_t i = 0; i < time_periods.size(); ++i)
             {
                 time_periods[i] = static_cast<T>(i + 1) / frequency;
             }
         }
Member Function Documentation
compute_cash_flows()
template<typename T > std::vector< T > bond::Bond< T >::compute_cash_flows () private
Calculate the cash flows of the bond.
Returns
The cash flows of the bonds (coupon payments)
Definition at line 133 of file bond.h.
     {
         assert(settlement_date < maturity_date);
         const T number_of_days_coupon = 365 / frequency;
         const auto days_difference = (maturity_date - settlement_date).count();
         const auto time_periods = static_cast<T>(days_difference) / number_of_days_coupon;
         const size_t num_time_periods = static_cast<size_t>(std::ceil(time_periods));
         std::vector<T> cash_flows(num_time_periods);
         for (auto& p : cash_flows)
         {
             p = coupon_value;
         }
         return cash_flows;
     }
compute_macaulay_duration()
template<typename T > T bond::Bond< T >::compute_macaulay_duration (const DF_type & df_type) const
Calculates the Macaulay duration of the bond.
Parameters
df_type The type of discount factor method
Returns
The Macaulay Duration of the bond
Discount factor
Prest cash flows
Present value
Macaulay duration
Definition at line 174 of file bond.h.
References irr::compute_discount_factor().
     {
         assert(yield > 0 && yield < 1);
         assert(cash_flows.size() > 0);
         assert(nominal_value > 0);
         assert(frequency > 0);
         T discount_factor = 0.0;
         T denominator = 0.0;
         T pv = 0.0;
         T numerator = 0.0;
         for (size_t i = 0; i < time_periods.size(); ++i)
         {
             discount_factor = compute_discount_factor(yield, time_periods[i], df_type);
             pv = coupon_value * discount_factor;
             numerator = numerator + pv * time_periods[i];
             denominator = denominator + pv;
         }
         pv = nominal_value * discount_factor;
         numerator = numerator + pv * time_periods.back();
         denominator = denominator + pv;
         T duration = numerator / denominator;
         return duration;
     }
compute_yield() [1/2]
template<typename T > template<typename S > T bond::Bond< T >::compute_yield (const T & i_price, const S & solver, const DF_type & df_type) const
Calculates the yield-to-maturity using the supplied solver.
Parameters
i_price The price of the bond
solver The parameter structure of the solver that is going to be used to estimate the yield of maturity
df_type The type of discount factor method
Returns
The yield-to-maturity of the bond
Definition at line 150 of file bond.h.
References irr::constraints_irr(), irr::fitness_irr(), and ea::solve().
     {
         assert(solver.ndv == 1);
         auto f = [&,use_penalty_method = solver.use_penalty_method](const auto& solution) { return fitness_irr(solution, i_price, nominal_value, cash_flows, time_periods, df_type, use_penalty_method); };
         auto c = [&,constraints_type = solver.constraints_type](const auto& solution) { return constraints_irr(solution, constraints_type); };
         auto res = solve(f, c, solver, "YTM");
         T yield = res[0];
         return yield;
     }
compute_yield() [2/2]
template<typename T > template<typename S > T bond::Bond< T >::compute_yield (const T & i_price, const S & solver, const DF_type & df_type, const std::string & bonds_identifier) const
Calculates the yield-to-maturity using the supplied solver and passes the bond identifier to the solver.
Parameters
i_price The price of the bond
solver The parameter structure of the solver that is going to be used to estimate the yield of maturity
df_type The type of discount factor method
bonds_identifier An identifier for the bond in std::string form
Returns
The yield-to-maturity of the bond
Definition at line 162 of file bond.h.
References irr::constraints_irr(), irr::fitness_irr(), and ea::solve().
     {
         assert(solver.ndv == 1);
         auto f = [&, use_penalty_method = solver.use_penalty_method](const auto& solution) { return fitness_irr(solution, i_price, nominal_value, cash_flows, time_periods, df_type, use_penalty_method); };
         auto c = [&, constraints_type = solver.constraints_type](const auto& solution) { return constraints_irr(solution, constraints_type); };
         std::string problem = "YTM";
         auto res = solve(f, c, solver, problem.append(bonds_identifier));
         T yield = res[0];
         return yield;
     }
Friends And Related Function Documentation
BondHelper< T >
template<typename T > friend class BondHelper< T > friend
Friend class BondHelper.
Definition at line 35 of file bond.h.
Member Data Documentation
cash_flows
template<typename T > std::vector<T> bond::Bond< T >::cash_flows private
A vector with all the coupon payments corresponding to time periods.
Definition at line 116 of file bond.h.
coupon_percentage
template<typename T > const T bond::Bond< T >::coupon_percentage private
Bond's annual coupon rate.
Definition at line 104 of file bond.h.
coupon_value
template<typename T > const T bond::Bond< T >::coupon_value private
This is the annual coupon divided by the frequency.
Definition at line 112 of file bond.h.
duration
template<typename T > T bond::Bond< T >::duration private
Macaulay duration of the bond.
Definition at line 124 of file bond.h.
frequency
template<typename T > const T bond::Bond< T >::frequency private
Bond's coupon payment frequency.
Definition at line 110 of file bond.h.
maturity_date
template<typename T > date::sys_days bond::Bond< T >::maturity_date private
Maturity date of the bond.
Definition at line 120 of file bond.h.
nominal_value
template<typename T > const T bond::Bond< T >::nominal_value private
Bond's face value.
Definition at line 108 of file bond.h.
price
template<typename T > const T bond::Bond< T >::price private
Bond's price.
Definition at line 106 of file bond.h.
settlement_date
template<typename T > date::sys_days bond::Bond< T >::settlement_date private
Settlement date of the bond.
Definition at line 118 of file bond.h.
time_periods
template<typename T > std::vector<T> bond::Bond< T >::time_periods private
Coupon payment periods.
Definition at line 114 of file bond.h.
yield
template<typename T > T bond::Bond< T >::yield private
Yield-to-maturity of the bond.
Definition at line 122 of file bond.h.
The documentation for this class was generated from the following file:
bond.h