Evolutionary Algorithms for Financial Optimisation: irr Namespace Reference
irr Namespace Reference
Internal Rate of Return (IRR) namespace.
Functions
template<typename T >
T compute_discount_factor (const T &r, const T &period, const DF_type &df_type)
Calculates discount factors.
template<typename T >
bool constraints_irr (const std::vector< T > &solution, const Constraints_type &constraints_type)
Constraints function for Internal Rate of Return.
template<typename T >
T compute_pv (const T &r, const T &nominal_value, const std::vector< T > &cash_flows, const std::vector< T > &time_periods, const DF_type &df_type)
Returns the present value of an investment.
template<typename T >
T penalty_irr (const T &r)
Penalty function for IRR.
template<typename T >
T fitness_irr (const std::vector< T > &solution, const T &price, const T &nominal_value, const std::vector< T > &cash_flows, const std::vector< T > &time_periods, const DF_type &df_type, const bool &use_penalty_method)
This is the fitness function for finding the internal rate of return of a bond, in this case it is equal to its yield to maturity.
Detailed Description
Internal Rate of Return (IRR) namespace.
Function Documentation
compute_discount_factor()
template<typename T > irr::compute_discount_factor (const T & r, const T & period, const DF_type & df_type)
Calculates discount factors.
Parameters
r Rate
period The period the rate was recorded
df_type The method used to calculate the discount factor
Returns
The discount factor
Definition at line 25 of file irr.h.
References utilities::exp, and utilities::frac.
Referenced by bond::Bond< T >::compute_macaulay_duration(), compute_pv(), and bond::BondHelper< T >::estimate_bond_pricing().
     {
         switch (df_type)
         {
         case (DF_type::frac): return 1 / std::pow((1 + r), period);
         case (DF_type::exp): return std::exp(-r * period);
             default: std::abort();
         }
     }
compute_pv()
template<typename T > irr::compute_pv (const T & r, const T & nominal_value, const std::vector< T > & cash_flows, const std::vector< T > & time_periods, const DF_type & df_type)
Returns the present value of an investment.
Parameters
r Internal Rate of Return
nominal_value The nominal value of the investment
cash_flows The cash flows of the investment
time_periods The time periods that correspond to the cash flows of the investment
df_type The method used to calculate the discount factor
Returns
The present value of the investment
Definition at line 74 of file irr.h.
References compute_discount_factor().
Referenced by fitness_irr().
     {
         assert(cash_flows.size() == time_periods.size());
         const size_t& num_time_periods =time_periods.size();
         T sum = 0.0;
         for (size_t i = 0; i < num_time_periods; ++i)
         {
             sum = sum + cash_flows[i] * compute_discount_factor(r, time_periods[i], df_type);
         }
         return sum + nominal_value * compute_discount_factor(r, time_periods.back(), df_type);
     }
constraints_irr()
template<typename T > irr::constraints_irr (const std::vector< T > & solution, const Constraints_type & constraints_type)
Constraints function for Internal Rate of Return.
Parameters
solution Internal Rate of Return candindate solution
constraints_type Type of constraints used
Returns
True if constraints are satisfied, false otherwise
Definition at line 42 of file irr.h.
References utilities::none, utilities::normal, and utilities::tight.
Referenced by bond::Bond< T >::compute_yield().
     {
         switch (constraints_type)
         {
         case(Constraints_type::normal):
         {
             const T& r = solution[0];
             if (r > 0 && r < 1)
             {
                 return true;
             }
             else
             {
                 return false;
             }
         }
         case(Constraints_type::tight): return true;
         case(Constraints_type::none): return true;
             default: std::abort();
         }
     }
fitness_irr()
template<typename T > irr::fitness_irr (const std::vector< T > & solution, const T & price, const T & nominal_value, const std::vector< T > & cash_flows, const std::vector< T > & time_periods, const DF_type & df_type, const bool & use_penalty_method)
This is the fitness function for finding the internal rate of return of a bond, in this case it is equal to its yield to maturity.
Parameters
solution Internal Rate of Return candindate solution
price The present value of the investment
nominal_value The nominal value of the investment
cash_flows The cash flows of the investment
time_periods The time periods that correspond to the cash flows of the investment
df_type The method used to calculate the discount factor
use_penalty_method Whether to use the penalty method defined for IRR or not
Returns
The fitness cost of IRR
Definition at line 116 of file irr.h.
References compute_pv(), and penalty_irr().
Referenced by bond::Bond< T >::compute_yield().
     {
         T sum_of_squares = 0;
         sum_of_squares = sum_of_squares + std::pow(price - compute_pv(solution[0], nominal_value, cash_flows, time_periods, df_type), 2);
         if (use_penalty_method)
         {
             return sum_of_squares + penalty_irr(solution[0]);
         }
         else
         {
             return sum_of_squares;
         }
     }
penalty_irr()
template<typename T > irr::penalty_irr (const T & r)
Penalty function for IRR.
Parameters
r Candidate solution for the Internal Rate of Return
Returns
A penalty value, if constraints are not satisfied
Definition at line 92 of file irr.h.
Referenced by fitness_irr().
     {
         T sum = 0;
         const T C = 1000;
         if (r < 0 || r > 1)
         {
             sum = sum + C * std::pow(std::abs(r), 2);
         }
         return sum;
     }