Evolutionary Algorithms for Financial Optimisation: nss Namespace Reference
nss Namespace Reference
Nelson-Siegel-Svensson (NSS) model namespace.
Functions
template<typename T >
bool constraints_svensson (const std::vector< T > &solution, const Constraints_type &constraints_type)
Constraints function for the NSS model.
template<typename T >
T svensson (const std::vector< T > &solution, const T &m)
Spot interest rate at term m using the NSS model.
template<typename T >
T penalty_svensson (const std::vector< T > &solution)
Penalty function for NSS.
Detailed Description
Nelson-Siegel-Svensson (NSS) model namespace.
Function Documentation
constraints_svensson()
template<typename T > nss::constraints_svensson (const std::vector< T > & solution, const Constraints_type & constraints_type)
Constraints function for the NSS model.
Parameters
solution NSS parameters candindate solution
constraints_type Type of constraints used
Returns
True if constraints are satisfied, false otherwise
Definition at line 18 of file svensson.h.
Referenced by bond::BondHelper< T >::bond_pricing(), and yft::Interest_Rate_Helper< T >::yieldcurve_fitting().
     {
         switch (constraints_type)
         {
         case(Constraints_type::normal):
         {
             const T& b0 = solution[0];
             const T& b1 = solution[1];
             const T& tau1 = solution[4];
             const T& tau2 = solution[5];
             if (b0 > 0 && b0 + b1 > 0 && tau1 > 0 && tau2 > 0)
             {
                 return true;
             }
             else
             {
                 return false;
             }
         }
         case(Constraints_type::tight):
         {
             const T& b0 = solution[0];
             const T& b1 = solution[1];
             const T& b2 = solution[2];
             const T& b3 = solution[3];
             const T& tau1 = solution[4];
             const T& tau2 = solution[5];
             if ((b0 > 0 && b0 < 15)
                 && (b1 > -15 && b1 < 30)
                 && (b2 > -30 && b2 < 30)
                 && (b3 > -30 && b3 < 30)
                 && (tau1 > 0 && tau1 < 2.5)
                 && (tau2 > 2.5 && tau2 < 5.5))
             {
                 return true;
             }
             else
             {
                 return false;
             }
         }
         case(Constraints_type::none): return true;
         default: std::abort();
         }
     }
penalty_svensson()
template<typename T > nss::penalty_svensson (const std::vector< T > & solution)
Penalty function for NSS.
Parameters
solution Candidate solution for the parameters of NSS
Returns
A penalty value, if constraints are not satisfied
Definition at line 99 of file svensson.h.
Referenced by bond::BondHelper< T >::fitness_bond_pricing_prices(), bond::BondHelper< T >::fitness_bond_pricing_yields(), and yft::Interest_Rate_Helper< T >::fitness_yield_curve_fitting().
     {
         T sum = 0;
         const T& b0 = solution[0];
         const T& b1 = solution[1];
         const T& b2 = solution[2];
         const T& b3 = solution[3];
         const T& tau1 = solution[4];
         const T& tau2 = solution[5];
         const T C = 100000;
         if (b0 < 0 || b0 > 15)
         {
             sum = sum + C * std::pow(std::abs(b0), 2);
         }
         if (b0 + b1 < 0)
         {
             sum = sum + C * std::pow(std::abs(b0 + b1), 2);
         }
         if (b1 < -15 || b1 > 30)
         {
             sum = sum + C * std::pow(std::abs(b1), 2);
         }
         if (b2 < -30 || b2 > 30)
         {
             sum = sum + C * std::pow(std::abs(b1), 2);
         }
         if (b3 < -30 || b3 > 30)
         {
             sum = sum + C * std::pow(std::abs(b1), 2);
         }
         if (tau1 < 0 || tau1 > 2.5)
         {
             sum = sum + C * std::pow(std::abs(tau2), 2);
         }
         if (tau2 < 2.5 || tau2 > 5.5)
         {
             sum = sum + C * std::pow(std::abs(tau2), 2);
         }
         return sum;
     }
svensson()
template<typename T > nss::svensson (const std::vector< T > & solution, const T & m)
Spot interest rate at term m using the NSS model.
Parameters
solution Candidate solution for the parameters of NSS
m The term at which the spot interest rate is recorded
Returns
The spot interest rate at term m
Definition at line 71 of file svensson.h.
Referenced by bond::BondHelper< T >::estimate_bond_pricing(), yft::Interest_Rate_Helper< T >::fitness_yield_curve_fitting(), and yft::Interest_Rate_Helper< T >::yieldcurve_fitting().
     {
         const T& b0 = solution[0];
         const T& b1 = solution[1];
         const T& b2 = solution[2];
         const T& b3 = solution[3];
         const T& tau1 = solution[4];
         const T& tau2 = solution[5];
         if (m == 0)
         {
             return b0 + b1;
         }
         else
         {
             T result = b0;
             result = result + b1 * ((1 - (std::exp(-m / tau1))) / (m / tau1));
             result = result + b2 * (((1 - (std::exp(-m / tau1))) / (m / tau1)) - std::exp(-m / tau1));
             result = result + b3 * (((1 - (std::exp(-m / tau2))) / (m / tau2)) - std::exp(-m / tau2));
             return result;
         }
     }