Evolutionary Algorithms for Financial Optimisation: ea Namespace Reference
ea Namespace Reference
Evolutionary Algorithms.
Classes
struct DE
Differential Evolution Structure, used in the actual algorithm and for type deduction.
struct EA_base
Evolutionary algorithm stucture base.
struct GA
Genetic Algorithms Structure, used in the actual algorithm and for type deduction.
struct PSOl
Local Best Particle Swarm Optimisation Structure, used in the actual algorithm and for type deduction.
struct PSOs
Particle Swarm Optimisation Structure, used in the actual algorithm and for type deduction.
class Solver
Template Class for Solvers.
class Solver< DE, T, F, C >
Differential Evolution Algorithm (DE) Class.
class Solver< GA, T, F, C >
Genetic Algorithms (GA) Class.
class Solver< PSOl, T, F, C >
Local Best Particle Swarm Optimisation (PSO) Class.
class Solver< PSOs, T, F, C >
Sub-Swarm Particle Swarm Optimisation (PSO) Class.
class Solver_base
Base Class for Evolutionary Algorithms.
Enumerations
enum Strategy { Strategy::keep_same, Strategy::re_mutate, Strategy::remove, Strategy::none }
Replacing or remove individuals strategies during mutation.
Functions
std::mt19937_64 generator (rd())
Pseudo-random number generator.
template<typename F , typename C , template< typename > class S, typename T >
std::vector< T > solve (const F &f, const C &c, const S< T > &solver_struct, const std::string &problem_name)
Solver wrapper function, interface to solvers : free function used for benchmarks.
Variables
std::random_device rd
Random device / Random number generator.
template<typename T >
const double inv_pi_sq = 1 / std::pow(boost::math::constants::pi<T>(), 2)
Inverse square of pi constant.
template<typename T >
const double inv_pi_sq_2 = 1 / std::pow(boost::math::constants::pi<T>(), 2)
Inverse square of pi constant.
Detailed Description
Evolutionary Algorithms.
Enumeration Type Documentation
Strategy
enum ea::Strategy strong
Replacing or remove individuals strategies during mutation.
Enumerator
keep_same
re_mutate
remove
none
Definition at line 15 of file geneticalgo.h.
 { keep_same, re_mutate, remove, none };
Function Documentation
generator()
ea::generator (rd())
Pseudo-random number generator.
Returns
A random number
Referenced by ea::Solver< DE, T, F, C >::construct_donor(), ea::Solver< DE, T, F, C >::construct_trial(), ea::Solver< GA, T, F, C >::crossover(), ea::Solver< PSOs, T, F, C >::generate_r(), ea::Solver< GA, T, F, C >::mutation(), ea::Solver< PSOl, T, F, C >::position_update(), ea::Solver_base< Solver< PSOl, T, F, C >, PSOl, T, F, C >::randomise_individual(), ea::Solver< GA, T, F, C >::selection(), and ea::Solver_base< Solver< PSOl, T, F, C >, PSOl, T, F, C >::Solver_base().
solve()
template<typename F , typename C , template< typename > class S, typename T > ea::solve (const F & f, const C & c, const S< T > & solver_struct, const std::string & problem_name)
Solver wrapper function, interface to solvers : free function used for benchmarks.
Parameters
f The objective function
c The constraints function
solver_struct The parameter structure of the solver
problem_name The name of the problem in std::string form. It is used to print results to file.
Returns
The solution vector
Definition at line 309 of file ealgorithm_base.h.
Referenced by bond::BondHelper< T >::bond_pricing(), bond::Bond< T >::compute_yield(), and yft::Interest_Rate_Helper< T >::yieldcurve_fitting().
     {
         Solver<S, T, F, C> solver{ solver_struct, f, c };
         return solver.solver_bench(problem_name);
     }
Variable Documentation
inv_pi_sq
template<typename T > const double ea::inv_pi_sq = 1 / std::pow(boost::math::constants::pi<T>(), 2)
Inverse square of pi constant.
Definition at line 307 of file lbestpso.h.
inv_pi_sq_2
template<typename T > const double ea::inv_pi_sq_2 = 1 / std::pow(boost::math::constants::pi<T>(), 2)
Inverse square of pi constant.
Definition at line 331 of file pso_sub_swarm.h.
rd
std::random_device ea::rd
Random device / Random number generator.
Definition at line 85 of file ealgorithm_base.h.